### ISSUE TITLE
docker build

### ISSUE THREAD

**Issue by spidero** [wiating-app/wiating_backend#6]
wiating_backend$ docker build . -t wiating_backend
Sending build context to Docker daemon  339.5kB
Step 1/11 : FROM debian:latest
latest: Pulling from library/debian
6a299ae9cfd9: Pull complete 
Digest: sha256:79becb70a6247d277b59c09ca340bbe0349af6aacb5afa90ec349528b53ce2c9
Status: Downloaded newer image for debian:latest
 ---> e3cbd207d8e5
Step 2/11 : RUN DEBIAN_FRONTEND=noninteractive apt-get update     && apt-get install -y curl git python3-pip python-setuptools python3-dev
 ---> Running in dc5136e0d3ec
Get:1 http://deb.debian.org/debian bookworm InRelease [151 kB]
Get:2 http://deb.debian.org/debian bookworm-updates InRelease [52.1 kB]
Get:3 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
Get:4 http://deb.debian.org/debian bookworm/main amd64 Packages [8787 kB]
Get:5 http://deb.debian.org/debian bookworm-updates/main amd64 Packages [12.7 kB]
Get:6 http://deb.debian.org/debian-security bookworm-security/main amd64 Packages [136 kB]
Fetched 9187 kB in 3s (2999 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
Package python-setuptools is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python-setuptools' has no installation candidate
The command '/bin/sh -c DEBIAN_FRONTEND=noninteractive apt-get update     && apt-get install -y curl git python3-pip python-setuptools python3-dev' returned a non-zero code: 100

**Comment by spidero** [comment]
```
git diff Dockerfile
diff --git a/Dockerfile b/Dockerfile
index 60bddb5..b5db303 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,7 +1,12 @@
 FROM debian:latest
 
 RUN DEBIAN_FRONTEND=noninteractive apt-get update \
-    && apt-get install -y curl git python3-pip python-setuptools python3-dev
+    && apt-get install -y curl git python3-pip python3-setuptools python3-dev python3-venv
+
+RUN python3 -m venv /opt/venv
+
+SHELL ["/bin/bash", "-c"]
+RUN source /opt/venv/bin/activate
 
 RUN mkdir -p /opt/wiating/devops
 RUN mkdir -p /images
@@ -9,7 +14,7 @@ RUN mkdir -p /images
 COPY requirements.txt .
 COPY requirements_test.txt .
 
-RUN pip3 install -r requirements_test.txt
+RUN /opt/venv/bin/pip install -r requirements_test.txt
 
 WORKDIR /opt/wiating
 

```

**Comment by merito** [comment]
1. I think specifying the base image version is needed to prevent failed builds in the future.
2. There is no need to use a virtual env in a container. This is why we use Docker to avoid having to use other env creation tools.

**Comment by spidero** [comment]
debian:latest is bookworm, which version did you use?

**Comment by merito** [comment]
Debian 10 buster is on prod

**Comment by merito** [comment]
I've pushed Debian release to backend (https://github.com/wiating-app/wiating_backend/commit/5f3353387276f3b0f3ead56d3313dec6f19ed9c2) and image resizer and fixed version of dependencies to image resizer too (https://github.com/wiating-app/image_resizer/commit/ddec0e547725908643a2e1344874114ff0ad830b)

**Comment by spidero** [comment]
> @spidero could you confirm that the fix is working?

build looks fine
